UNAME_S := $(shell uname -s)
CMAKEFLAGS :=-DDAWN_FETCH_DEPENDENCIES=ON -DDAWN_ENABLE_INSTALL=ON -DCMAKE_BUILD_TYPE=Release 

ifeq ($(UNAME_S),Linux)
    CMAKEFLAGS +=-DDAWN_USE_WAYLAND=ON 
endif

build:
	@echo "Building in $(CURDIR)" 
	cmake -S . -B out/Release ${CMAKEFLAGS}
	cmake --build out/Release

install:
	@echo "Installing in $(CURDIR)" 
	cmake --install out/Release --prefix ../../sysroot/

update:
	git pull origin main

.PHONY: build install update
