build:
	@echo "Building in $(CURDIR)" 
	cmake -S . -B out/Release -DLIBTYPE=STATIC 
	cmake --build out/Release

install:
	@echo "Installing in $(CURDIR)" 
	cmake --install out/Release --prefix ../../sysroot/

update:
	git reset HEAD --hard
	git pull origin master

.PHONY: build install update
