build:
	@echo "Building in $(CURDIR)" 
	cmake -S . -B out/Release -DGLFW_LIBRARY_TYPE=STATIC -DCMAKE_BUILD_TYPE=Release
	cmake --build out/Release

install:
	@echo "Installing in $(CURDIR)" 
	cmake --install out/Release --prefix ../../sysroot/

update:
	git pull

.PHONY: build install update
